services:
  saml-lab:
    build: .
    container_name: sso-sandbox
    restart: unless-stopped
    environment:
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
      - SAML_IDP_ENTITY_ID=${SAML_IDP_ENTITY_ID}
      - SAML_IDP_SSO_URL=${SAML_IDP_SSO_URL}
      - SAML_IDP_X509CERT=${SAML_IDP_X509CERT}
      - SAML_DEBUG=${SAML_DEBUG}
      - SAML_ENABLE_SLO=${SAML_ENABLE_SLO}

      # Email relay parameters via Postfix relay - using OAuth2
      - MAIL_DRIVER=smtp
      - MAIL_HOST=mail-relay   # Postfix-relay container name — Docker DNS resolves this
      - MAIL_PORT=25
      - MAIL_ENCRYPTION=null
      - MAIL_FROM=${SMTP_FROM_ADDRESS}
      - MAIL_FROM_NAME=BookStack
      
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sso-sandbox.rule=Host(`sso-sandbox.aktechnoservices.com`)"
      - "traefik.http.routers.sso-sandbox.entrypoints=websecure"
      - "traefik.http.routers.sso-sandbox.tls.certresolver=cloudflare"
      - "traefik.http.routers.sso-sandbox.middlewares=secured-chain@docker"
      - "traefik.http.services.sso-sandbox.loadbalancer.server.port=5000"
    
    networks:
      - reverse-proxy                  #same network with Postfix-relay
   
networks:
  reverse-proxy:
    external: true
