services:
  identity-integration:
    image: akwizzy/pilot-repo:identity-integration
    container_name: identity-integration
    restart: unless-stopped

    environment:
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
      - SAML_IDP_ENTITY_ID=${SAML_IDP_ENTITY_ID}
      - SAML_IDP_SSO_URL=${SAML_IDP_SSO_URL}
      - SAML_IDP_X509CERT=${SAML_IDP_X509CERT}
      - SAML_DEBUG=${SAML_DEBUG}
      - SAML_ENABLE_SLO=${SAML_ENABLE_SLO}

      # Showcase Framework
      - APP_VERSION=${APP_VERSION}

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.identity-integration.rule=Host(`identity-integration.aktechnoservices.com`)"
      - "traefik.http.routers.identity-integration.entrypoints=websecure"
      - "traefik.http.routers.identity-integration.tls.certresolver=cloudflare"
      - "traefik.http.routers.identity-integration.middlewares=secured-chain@docker"
      - "traefik.http.services.identity-integration.loadbalancer.server.port=5000"

    networks:
      - reverse-proxy

networks:
  reverse-proxy:
    external: true